/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    ButtonGroup: typeof import('primevue/buttongroup')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    InputOtp: typeof import('primevue/inputotp')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Link: typeof import('./src/components/link.vue')['default']
    Login: typeof import('./src/components/login.vue')['default']
    Select: typeof import('primevue/select')['default']
    Titlebar: typeof import('./src/components/titlebar.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
